#!/usr/bin/env bash

dirs=(
    ~/work
    ~/git
    ~/.config
    ~/dotfiles/
)

preview_command="eza --tree {} --color"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
        fd \
            '.' \
            --min-depth 1 \
            --max-depth 1 \
            --type d \
            "${dirs[@]}" |
            fzf \
                --tmux \
                --no-multi \
                --preview "${preview_command}" \
                --prompt 'Select Workspace: ' \
                --preview-label 'Workspace Files' \
                --preview-window 'right:30%'
    )
fi

[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
