require('user.plugins')
require('user.treesitter')
require('user.mappings')
require('user.set')
require('user.filetype')
require('user.filetree')
require('user.lsp')
require('user.statusline')
require('user.completion')
require('user.bufferline')

