import = ["/home/george/.config/alacritty/themes/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 300
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
style = "Medium"

[font.italic]
style = "Light"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[shell]
program = "tmux"

[window]
decorations = "none"
