# Taps
tap "homebrew/cask-fonts"

# Casks

# TTY
cask "alacritty"

# Fonts
cask "font-fira-code-nerd-font"

## Keyboard
cask "via"
cask "keycastr"

## Webcam
cask "elgato-camera-hub"

## Browser
cask "firefox"

## Media Players
cask "spotify"
cask "vlc"

## Password
cask "1password"
cask "1password/tap/1password-cli"

## Chat
cask "slack"
cask "microsoft-teams"
cask "discord"
cask "zoom"
cask "obs"

## Text Editors
cask "macdown"

## Dev
cask "visual-studio-code"

## Layout
cask "rectangle"

# Formula

## Shell
brew "chezmoi"
brew "antigen"

## Command Line Tools
brew "dog"      # dig
brew "bat"      # cat
brew "exa"      # ls
brew "fd"       # find
brew "fzf"      # fuzzy search
brew "ripgrep"  # grep
brew "glow"     # markdown reader
brew "tmux"     # session manager
brew "graphviz" # graph vizualizer
brew "zoxide"   # cd with memory z
brew "starship" # prompt

## Text Editors
brew "neovim"

## Filtering
brew "yq"
brew "jq"

## HTTP
brew "httpie"
brew "wget"
brew "curl"

## Git
brew "git"
brew "gh"
brew "git-delta"

## AWS
brew "awscli"
brew "cfn-lint"
brew "rain"

## Languages and Language Tools

### Python
brew "pyenv"
brew "pipx"
brew "pipenv"

### Ruby
brew "rbenv"

### Go
brew "go"

### Rust
brew "rustup"

### Node
brew "nvm"

### Terraform
brew "tflint"
brew "tfenv"

### Development Workflow
brew "pre-commit"
brew "docker"
brew "make"
brew "spectral-cli"
brew "exercism"
brew "lazygit"
